# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: LOCAL
      POSTGRES_PASSWORD: LOCAL
      POSTGRES_DB: WALLET
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
